### ISSUE TITLE
ラズパイだけで完結させる

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [0g3/locube#2]
既存のMac&Arduinoという構成をラズベリーパイ一台で統合する。

**Comment by Nagisa-Takeuchi** [comment]
トランジスタを用いて信号を増幅しようとしたが、仕様上トランジスタをGND側に置かねばならず、信号線にGNDが無いため不可能であった。
トランジスタは電気を引き込むことはできるが、押し出すことはできない。
機構的にはリレーを用いるべきところであるが、高速スイッチングができないため実質使用不能。

**Comment by 0g3** [comment]
りょーかい。
